--! @file        xwb_serdes_clk_gen_auto_pkg.vhd
--  DesignUnit   xwb_serdes_clk_gen_auto
--! @author      Theodor Stana <>
--! @date        24/03/2015
--! @version     
--! @copyright   2015 GSI Helmholtz Centre for Heavy Ion Research GmbH
--!

--! @brief AUTOGENERATED WISHBONE-SLAVE PACKAGE FOR xwb_serdes_clk_gen.vhd
--!
--------------------------------------------------------------------------------
--! This library is free software; you can redistribute it and/or
--! modify it under the terms of the GNU Lesser General Public
--! License as published by the Free Software Foundation; either
--! version 3 of the License, or (at your option) any later version.
--!
--! This library is distributed in the hope that it will be useful,
--! but WITHOUT ANY WARRANTY; without even the implied warranty of
--! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--! Lesser General Public License for more details.
--!
--! You should have received a copy of the GNU Lesser General Public
--! License along with this library. If not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

-- ***********************************************************
-- ** WARNING - THIS IS AUTO-GENERATED CODE! DO NOT MODIFY! **
-- ***********************************************************
--
-- If you want to change the interface,
-- modify xwb_serdes_clk_gen.xml and re-run 'python wbgenplus.py xwb_serdes_clk_gen.xml' !

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
package xwb_serdes_clk_gen_auto_pkg is

   --+******************************************************************************************+
   --|  ------------------------------- WB Slaves - Adress Maps --------------------------------|
   --+******************************************************************************************+

   --| WBS Adr ------------------------------- wbs ---------------------------------------------|
      constant c_wbs_selr_RW     : natural   := 16#0#;   -- rw 0xffffffff, Selects which channel to control.
      constant c_wbs_hperr_RW    : natural   := 16#4#;   -- rw 0xffffffff, Half-period register
      constant c_wbs_maskr_RW    : natural   := 16#8#;   -- rw 0xffffffff, Bit flip mask register

   --+******************************************************************************************+
   --|  ------------------------- WB Slaves - Control Register Records -------------------------|
   --+******************************************************************************************+

   --| WBS Register Record ------------- wbs ---------------------------------------------------|
   
   subtype t_slv_wbs_hperr is std_logic_vector(32-1 downto 0);
   type    t_slv_wbs_hperr_array is array(natural range <>) of t_slv_wbs_hperr;
   
   subtype t_slv_wbs_maskr is std_logic_vector(32-1 downto 0);
   type    t_slv_wbs_maskr_array is array(natural range <>) of t_slv_wbs_maskr;
   
   type t_wbs_regs_o is record
      selr  : std_logic_vector(32-1 downto 0);     -- Selects which channel to control.
      hperr : t_slv_wbs_hperr_array(0-1 downto 0); -- Half-period register
      maskr : t_slv_wbs_maskr_array(0-1 downto 0); -- Bit flip mask register
   end record t_wbs_regs_o;

   type t_wbs_regs_clk_sys_o is record
      selr  : std_logic_vector(32-1 downto 0);     -- Selects which channel to control.
   end record t_wbs_regs_clk_sys_o;

   type t_wbs_regs_clk_ref_o is record
      hperr : t_slv_wbs_hperr_array(0-1 downto 0); -- Half-period register
      maskr : t_slv_wbs_maskr_array(0-1 downto 0); -- Bit flip mask register
   end record t_wbs_regs_clk_ref_o;

   type t_wbs_regs_i is record
      STALL : std_logic;                           -- Stall control for outside entity
      ERR   : std_logic;                           -- Error control for outside entity
   end record t_wbs_regs_i;

   type t_wbs_regs_clk_sys_i is record
      STALL : std_logic;                           -- Stall control for outside entity
      ERR   : std_logic;                           -- Error control for outside entity
   end record t_wbs_regs_clk_sys_i;

   --| Component ------------------ xwb_serdes_clk_gen_auto ------------------------------------|
   component xwb_serdes_clk_gen_auto is
   Port(
      clk_sys_i            : in  std_logic;
      clk_ref_i            : in  std_logic;
      rst_n_i              : in  std_logic;

      wbs_regs_clk_sys_o   : out t_wbs_regs_clk_sys_o;
      wbs_regs_clk_ref_o   : out t_wbs_regs_clk_ref_o;
      wbs_regs_clk_sys_i   : in  t_wbs_regs_clk_sys_i;
      wbs_i                : in  t_wishbone_slave_in;
      wbs_o                : out t_wishbone_slave_out
      
   );
   end component;

   constant c_xwb_serdes_clk_gen_wbs_sdb : t_sdb_device := (
   abi_class     => x"0000", -- undocumented device
   abi_ver_major => x"01",
   abi_ver_minor => x"00",
   wbd_endian    => c_sdb_endian_big,
   wbd_width     => x"7", -- 8/16/32-bit port granularity
   sdb_component => (
   addr_first    => x"0000000000000000",
   addr_last     => x"000000000000000f",
   product => (
   vendor_id     => x"0000000000000651",
   device_id     => x"c3961dd6",
   version       => x"00000000",
   date          => x"20150324",
   name          => "xwb_serdes_clk_gen ")));
   
end xwb_serdes_clk_gen_auto_pkg;
package body xwb_serdes_clk_gen_auto_pkg is
end xwb_serdes_clk_gen_auto_pkg;
