#! /bin/sh

dev="$1"
set -e

echo -n "Configuring ECA: "

eca-ctl $dev enable
eca-ctl $dev idisable # No interrupts, please

eca-table $dev flush

#channel 0 should be lemo out, try 'eca-table -h' for help
eca-ctl $dev activate -c 0
eca-table $dev add 0xdeadbeef/64 0 0 0x1  # set bit 0
eca-table $dev add 0xdeadbeef/64 62500000 0 0x10000 # clear bit 0

eca-table $dev flip-active

echo "done."


echo -n "Pulse? "
period=125000000
last=0
while true; do
 # Try to schedule next pulse 3x a second.
 # This way we don't miss any pulses due to slow scheduling on linux.
 sleep 0.3
 # What time is it?
 when=`eca-ctl $dev -n | grep time | cut -d: -f2`
 # Round up to the next second.
 next="$(((when+period+period-1)/period*period))"
 # If we haven't scheduled this PPS pulse yet, do it now. 
 if [ $next -ne $last ]; then 
   eca-ctl $dev send 0xdeadbeef 0 0 $next
   echo "now"
   echo -n "Pulse? "
 else
   echo -n ". "
 fi
 last="$next"
done

